In [2]:
#Method 1

In [1]:
import pandas as pd
import understatapi

client=understatapi.UnderstatClient()

In [3]:
league_data=client.league(league="Serie_A").get_match_data(season="2024")

In [4]:
league_data[0]

{'id': '27362',
 'isResult': True,
 'h': {'id': '101', 'title': 'Genoa', 'short_title': 'GEN'},
 'a': {'id': '106', 'title': 'Inter', 'short_title': 'INT'},
 'goals': {'h': '2', 'a': '2'},
 'xG': {'h': '2.31286', 'a': '2.00656'},
 'datetime': '2024-08-17 16:30:00',
 'forecast': {'w': '0.4556', 'd': '0.2689', 'l': '0.2755'}}

In [5]:
shot_data=client.match(match="27362").get_shot_data()

In [7]:
shot_data["h"][0]

{'id': '584922',
 'minute': '17',
 'result': 'SavedShot',
 'X': '0.84',
 'Y': '0.5770000076293945',
 'xG': '0.28586047887802124',
 'player': 'Vitinha',
 'h_a': 'h',
 'player_id': '11380',
 'situation': 'OpenPlay',
 'season': '2024',
 'shotType': 'RightFoot',
 'match_id': '27362',
 'h_team': 'Genoa',
 'a_team': 'Inter',
 'h_goals': '2',
 'a_goals': '2',
 'date': '2024-08-17 16:30:00',
 'player_assisted': 'Milan Badelj',
 'lastAction': 'Chipped'}

In [8]:
player_data=client.player(player="11380").get_shot_data()

In [10]:
player_data[0]

{'id': '507886',
 'minute': '42',
 'result': 'MissedShots',
 'X': '0.9019999694824219',
 'Y': '0.645',
 'xG': '0.07335619628429413',
 'player': 'Vitinha',
 'h_a': 'h',
 'player_id': '11380',
 'situation': 'OpenPlay',
 'season': '2022',
 'shotType': 'LeftFoot',
 'match_id': '19862',
 'h_team': 'Marseille',
 'a_team': 'Nice',
 'h_goals': '1',
 'a_goals': '3',
 'date': '2023-02-05 19:45:00',
 'player_assisted': 'Nuno Tavares',
 'lastAction': 'Pass'}

In [11]:
df=pd.DataFrame(player_data)

In [12]:
df.head()

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,507886,42,MissedShots,0.9019999694824219,0.645,0.07335619628429413,Vitinha,h,11380,OpenPlay,2022,LeftFoot,19862,Marseille,Nice,1,3,2023-02-05 19:45:00,Nuno Tavares,Pass
1,511556,89,SavedShot,0.9540000152587891,0.5209999847412109,0.546347975730896,Vitinha,h,11380,OpenPlay,2022,RightFoot,19896,Marseille,Paris Saint Germain,0,3,2023-02-26 19:45:00,Nuno Tavares,Cross
2,520345,1,Goal,0.9,0.3679999923706055,0.1280760020017624,Vitinha,h,11380,OpenPlay,2022,RightFoot,19952,Marseille,Troyes,3,1,2023-04-16 18:45:00,Alexis Sánchez,TakeOn
3,520347,6,SavedShot,0.915,0.3340000152587891,0.08543159812688828,Vitinha,h,11380,OpenPlay,2022,RightFoot,19952,Marseille,Troyes,3,1,2023-04-16 18:45:00,None,BallTouch
4,520351,11,MissedShots,0.9740000152587891,0.5620000076293945,0.6314340233802795,Vitinha,h,11380,OpenPlay,2022,RightFoot,19952,Marseille,Troyes,3,1,2023-04-16 18:45:00,Cengiz Ünder,Rebound

In [13]:
df_league=pd.DataFrame(league_data)

In [15]:
df_league

,id,isResult,h,a,goals,xG,datetime,forecast
0,27362,True,"{'id': '101', 'title': 'Genoa', 'short_title':...","{'id': '106', 'title': 'Inter', 'short_title':...","{'h': '2', 'a': '2'}","{'h': '2.31286', 'a': '2.00656'}",2024-08-17 16:30:00,"{'w': '0.4556', 'd': '0.2689', 'l': '0.2755'}"
1,27363,True,"{'id': '230', 'title': 'Parma Calcio 1913', 's...","{'id': '110', 'title': 'Fiorentina', 'short_ti...","{'h': '1', 'a': '1'}","{'h': '1.83796', 'a': '0.81313'}",2024-08-17 16:30:00,"{'w': '0.6549', 'd': '0.2172', 'l': '0.1279'}"
2,27364,True,"{'id': '108', 'title': 'Empoli', 'short_title'...","{'id': '271', 'title': 'Monza', 'short_title':...","{'h': '0', 'a': '0'}","{'h': '0.578573', 'a': '0.327848'}",2024-08-17 18:45:00,"{'w': '0.3458', 'd': '0.4817', 'l': '0.1725'}"
3,27365,True,"{'id': '111', 'title': 'AC Milan', 'short_titl...","{'id': '113', 'title': 'Torino', 'short_title'...","{'h': '2', 'a': '2'}","{'h': '2.1004', 'a': '0.876602'}",2024-08-17 18:45:00,"{'w': '0.6938', 'd': '0.2176', 'l': '0.0886'}"
4,27366,True,"{'id': '94', 'title': 'Verona', 'short_title':...","{'id': '105', 'title': 'Napoli', 'short_title'...","{'h': '3', 'a': '0'}","{'h': '1.80536', 'a': '0.975176'}",2024-08-18 16:30:00,"{'w': '0.6173', 'd': '0.2346', 'l': '0.1481'}"
...,...,...,...,...,...,...,...,...
375,27733,True,"{'id': '107', 'title': 'Atalanta', 'short_titl...","{'id': '230', 'title': 'Parma Calcio 1913', 's...","{'h': '2', 'a': '3'}","{'h': '1.90265', 'a': '2.82535'}",2025-05-25 18:45:00,"{'w': '0.2185', 'd': '0.1982', 'l': '0.5833'}"
376,27736,True,"{'id': '108', 'title': 'Empoli', 'short_title'...","{'id': '94', 'title': 'Verona', 'short_title':...","{'h': '1', 'a': '2'}","{'h': '1.23351', 'a': '0.833807'}",2025-05-25 18:45:00,"{'w': '0.4435', 'd': '0.4126', 'l': '0.1439'}"
377,27737,True,"{'id': '96', 'title': 'Lazio', 'short_title': ...","{'id': '243', 'title': 'Lecce', 'short_title':...","{'h': '0', 'a': '1'}","{'h': '1.73521', 'a': '0.708667'}",2025-05-25 18:45:00,"{'w': '0.6342', 'd': '0.2364', 'l': '0.1294'}"
378,27740,True,"{'id': '113', 'title': 'Torino', 'short_title'...","{'id': '95', 'title': 'Roma', 'short_title': '...","{'h': '0', 'a': '2'}","{'h': '0.381059', 'a': '2.64436'}",2025-05-25 18:45:00,"{'w': '0.0183', 'd': '0.0708', 'l': '0.9109'}"
379,27741,True,"{'id': '99', 'title': 'Udinese', 'short_title'...","{'id': '110', 'title': 'Fiorentina', 'short_ti...","{'h': '2', 'a': '3'}","{'h': '1.61711', 'a': '3.06465'}",2025-05-25 18:45:00,"{'w': '0.1113', 'd': '0.1785', 'l': '0.7102'}"

In [17]:
team_match_data = client.team(team="Manchester_United").get_match_data(season="2019")

In [18]:
df_mun=pd.DataFrame(team_match_data)

In [19]:
df_mun.head()

,id,isResult,side,h,a,goals,xG,datetime,forecast,result
0,11652,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '80', 'title': 'Chelsea', 'short_title'...","{'h': '4', 'a': '0'}","{'h': '2.37442', 'a': '1.09534'}",2019-08-11 16:30:00,"{'w': 0.6573873021952279, 'd': 0.1826644677346...",w
1,11662,True,a,"{'id': '229', 'title': 'Wolverhampton Wanderer...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '0.307356', 'a': '1.14332'}",2019-08-19 20:00:00,"{'w': 0.09923489359411587, 'd': 0.324311051358...",d
2,11669,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '78', 'title': 'Crystal Palace', 'short...","{'h': '1', 'a': '2'}","{'h': '2.23561', 'a': '0.676993'}",2019-08-24 15:00:00,"{'w': 0.7291315176890407, 'd': 0.1734423536622...",l
3,11673,True,a,"{'id': '74', 'title': 'Southampton', 'short_ti...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '0.769616', 'a': '1.90356'}",2019-08-31 12:30:00,"{'w': 0.14428310075367692, 'd': 0.213821719325...",d
4,11684,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '75', 'title': 'Leicester', 'short_titl...","{'h': '1', 'a': '0'}","{'h': '1.10019', 'a': '0.459141'}",2019-09-14 14:00:00,"{'w': 0.515784016272218, 'd': 0.33068751880377...",w

In [20]:
df_mun

,id,isResult,side,h,a,goals,xG,datetime,forecast,result
0,11652,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '80', 'title': 'Chelsea', 'short_title'...","{'h': '4', 'a': '0'}","{'h': '2.37442', 'a': '1.09534'}",2019-08-11 16:30:00,"{'w': 0.6573873021952279, 'd': 0.1826644677346...",w
1,11662,True,a,"{'id': '229', 'title': 'Wolverhampton Wanderer...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '0.307356', 'a': '1.14332'}",2019-08-19 20:00:00,"{'w': 0.09923489359411587, 'd': 0.324311051358...",d
2,11669,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '78', 'title': 'Crystal Palace', 'short...","{'h': '1', 'a': '2'}","{'h': '2.23561', 'a': '0.676993'}",2019-08-24 15:00:00,"{'w': 0.7291315176890407, 'd': 0.1734423536622...",l
3,11673,True,a,"{'id': '74', 'title': 'Southampton', 'short_ti...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '0.769616', 'a': '1.90356'}",2019-08-31 12:30:00,"{'w': 0.14428310075367692, 'd': 0.213821719325...",d
4,11684,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '75', 'title': 'Leicester', 'short_titl...","{'h': '1', 'a': '0'}","{'h': '1.10019', 'a': '0.459141'}",2019-09-14 14:00:00,"{'w': 0.515784016272218, 'd': 0.33068751880377...",w
5,11700,True,a,"{'id': '81', 'title': 'West Ham', 'short_title...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '2', 'a': '0'}","{'h': '0.51376', 'a': '1.27826'}",2019-09-22 13:00:00,"{'w': 0.1492182646044257, 'd': 0.2953793375174...",l
6,11712,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '83', 'title': 'Arsenal', 'short_title'...","{'h': '1', 'a': '1'}","{'h': '1.1335', 'a': '1.70399'}",2019-09-30 19:00:00,"{'w': 0.25327211557627644, 'd': 0.239585283263...",d
7,11721,True,a,"{'id': '86', 'title': 'Newcastle United', 'sho...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '0'}","{'h': '0.650296', 'a': '0.969204'}",2019-10-06 16:30:00,"{'w': 0.2377171949977939, 'd': 0.3438853373360...",l
8,11729,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '87', 'title': 'Liverpool', 'short_titl...","{'h': '1', 'a': '1'}","{'h': '0.791862', 'a': '1.03212'}",2019-10-20 16:30:00,"{'w': 0.27347430359760694, 'd': 0.322804908614...",d
9,11739,True,a,"{'id': '79', 'title': 'Norwich', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '3'}","{'h': '0.8924', 'a': '4.51232'}",2019-10-27 16:30:00,"{'w': 0.02717715358633167, 'd': 0.051396031789...",w
10,11745,True,a,"{'id': '73', 'title': 'Bournemouth', 'short_ti...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '0'}","{'h': '1.86862', 'a': '0.641129'}",2019-11-02 12:30:00,"{'w': 0.6676787854980799, 'd': 0.2120300780127...",l
11,11761,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '220', 'title': 'Brighton', 'short_titl...","{'h': '3', 'a': '1'}","{'h': '3.65299', 'a': '1.1342'}",2019-11-10 14:00:00,"{'w': 0.826813484728571, 'd': 0.10017585580676...",w
12,11770,True,a,"{'id': '238', 'title': 'Sheffield United', 'sh...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '3', 'a': '3'}","{'h': '1.56025', 'a': '1.33065'}",2019-11-24 16:30:00,"{'w': 0.42802927537206037, 'd': 0.246393249282...",d
13,11782,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '71', 'title': 'Aston Villa', 'short_ti...","{'h': '2', 'a': '2'}","{'h': '1.84804', 'a': '1.29701'}",2019-12-01 16:30:00,"{'w': 0.50361660560937, 'd': 0.227336817955676...",d
14,11788,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '82', 'title': 'Tottenham', 'short_titl...","{'h': '2', 'a': '1'}","{'h': '1.47683', 'a': '0.542315'}",2019-12-04 19:30:00,"{'w': 0.6024513867178972, 'd': 0.2623883883509...",w
15,11797,True,a,"{'id': '88', 'title': 'Manchester City', 'shor...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '2'}","{'h': '2.07108', 'a': '1.63385'}",2019-12-07 17:30:00,"{'w': 0.4812111253950325, 'd': 0.2111888019564...",w
16,11809,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '72', 'title': 'Everton', 'short_title'...","{'h': '1', 'a': '1'}","{'h': '1.48327', 'a': '0.276759'}",2019-12-15 14:00:00,"{'w': 0.6834117906686864, 'd': 0.2502508041849...",d
17,11821,True,a,"{'id': '90', 'title': 'Watford', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '2', 'a': '0'}","{'h': '1.59291', 'a': '1.5309'}",2019-12-22 14:00:00,"{'w': 0.3947089659791913, 'd': 0.2373612260446...",l
18,11829,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '86', 'title': 'Newcastle United', 'sho...","{'h': '4', 'a': '1'}","{'h': '1.99638', 'a': '1.05018'}",2019-12-26 17:30:00,"{'w': 0.5930334261102183, 'd': 0.2132774760900...",w
19,11835,True,a,"{'id': '92', 'title': 'Burnley', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '2'}","{'h': '0.386662', 'a': '2.10542'}",2019-12-28 19:45:00,"{'w': 0.05601971931072374, 'd': 0.165106425136...",w
20,11844,True,a,"{'id': '83', 'title': 'Arsenal', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '2', 'a': '0'}","{'h': '1.90747', 'a': '0.715563'}",2020-01-01 20:00:00,"{'w': 0.6565452901862939, 'd': 0.2110452381128...",l
21,11862,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '79', 'title': 'Norwich', 'short_title'...","{'h': '4', 'a': '0'}","{'h': '3.13456', 'a': '0.275987'}",2020-01-11 15:00:00,"{'w': 0.9161194753995396, 'd': 0.0683970979654...",w
22,11865,True,a,"{'id': '87', 'title': 'Liverpool', 'short_titl...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '2', 'a': '0'}","{'h': '2.00655', 'a': '1.4185'}",2020-01-19 16:30:00,"{'w': 0.5122543190829604, 'd': 0.2161217685359...",l
23,11879,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '92', 'title': 'Burnley', 'short_title'...","{'h': '0', 'a': '2'}","{'h': '1.416', 'a': '0.717284'}",2020-01-22 20:15:00,"{'w': 0.5375956436321254, 'd': 0.2729747353582...",l
24,11888,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '229', 'title': 'Wolverhampton Wanderer...","{'h': '0', 'a': '0'}","{'h': '1.18608', 'a': '1.54211'}",2020-02-01 17:30:00,"{'w': 0.29277588480320943, 'd': 0.251963336194...",d
25,11896,True,a,"{'id': '80', 'title': 'Chelsea', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '2'}","{'h': '0.940204', 'a': '0.681814'}",2020-02-17 20:00:00,"{'w': 0.40034106463756614, 'd': 0.345900454467...",w
26,11910,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '90', 'title': 'Watford', 'short_title'...","{'h': '3', 'a': '0'}","{'h': '2.5042', 'a': '0.294956'}",2020-02-23 14:00:00,"{'w': 0.8560222177530143, 'd': 0.1148301429033...",w
27,11916,True,a,"{'id': '72', 'title': 'Everton', 'short_title'...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '2.41259', 'a': '1.12561'}",2020-03-01 14:00:00,"{'w': 0.657640580242263, 'd': 0.18082007141240...",d
28,11932,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '88', 'title': 'Manchester City', 'shor...","{'h': '2', 'a': '0'}","{'h': '1.7389', 'a': '0.585469'}",2020-03-08 16:30:00,"{'w': 0.6542050201239356, 'd': 0.2258700912299...",w
29,11936,True,a,"{'id': '82', 'title': 'Tottenham', 'short_titl...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '1', 'a': '1'}","{'h': '0.534852', 'a': '1.77307'}",2020-06-19 19:15:00,"{'w': 0.10568987318035811, 'd': 0.218661101354...",d
30,11950,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '238', 'title': 'Sheffield United', 'sh...","{'h': '3', 'a': '0'}","{'h': '2.8416', 'a': '0.108082'}",2020-06-24 17:00:00,"{'w': 0.9233617721881863, 'd': 0.0697139358069...",w
31,11956,True,a,"{'id': '220', 'title': 'Brighton', 'short_titl...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '3'}","{'h': '0.31013', 'a': '1.20903'}",2020-06-30 19:15:00,"{'w': 0.09463055678015914, 'd': 0.308993962104...",w
32,11967,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '73', 'title': 'Bournemouth', 'short_ti...","{'h': '5', 'a': '2'}","{'h': '2.63259', 'a': '1.52161'}",2020-07-04 14:00:00,"{'w': 0.6137452572164355, 'd': 0.1778642952442...",w
33,11974,True,a,"{'id': '71', 'title': 'Aston Villa', 'short_ti...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '3'}","{'h': '0.598873', 'a': '2.86531'}",2020-07-09 19:15:00,"{'w': 0.051694203017158644, 'd': 0.11294311434...",w
34,11987,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '74', 'title': 'Southampton', 'short_ti...","{'h': '2', 'a': '2'}","{'h': '1.5033', 'a': '1.8051'}",2020-07-13 19:00:00,"{'w': 0.32305318816410306, 'd': 0.227302326201...",d
35,11996,True,a,"{'id': '78', 'title': 'Crystal Palace', 'short...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '2'}","{'h': '0.572141', 'a': '1.90448'}",2020-07-16 19:15:00,"{'w': 0.10290165181526423, 'd': 0.203760387387...",w
36,12007,True,h,"{'id': '89', 'title': 'Manchester United', 'sh...","{'id': '81', 'title': 'West Ham', 'short_title...","{'h': '1', 'a': '1'}","{'h': '0.984161', 'a': '1.29009'}",2020-07-22 17:00:00,"{'w': 0.2837536149080415, 'd': 0.2812846220482...",d
37,12018,True,a,"{'id': '75', 'title': 'Leicester', 'short_titl...","{'id': '89', 'title': 'Manchester United', 'sh...","{'h': '0', 'a': '2'}","{'h': '0.754668', 'a': '1.41019'}",2020-07-26 15:00:00,"{'w': 0.200451884625586, 'd': 0.27350797917150...",w

In [21]:
#Method 2

In [22]:
import re
import requests
import json
from bs4 import BeautifulSoup

In [23]:
response=requests.get("https://understat.com/match/28837")
response.status_code

200

In [24]:
soup=BeautifulSoup(response.content, "html.parser")
ugly_soup=str(soup)

In [25]:
shots_data=re.search("var shotsData .*= JSON.parse\('(.*)'\)", ugly_soup).group(1)

In [26]:
shots_data

'\\x7B\\x22h\\x22\\x3A\\x5B\\x7B\\x22id\\x22\\x3A\\x22645722\\x22,\\x22minute\\x22\\x3A\\x2214\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.9109999847412109\\x22,\\x22Y\\x22\\x3A\\x220.455\\x22,\\x22xG\\x22\\x3A\\x220.259369432926178\\x22,\\x22player\\x22\\x3A\\x22Beto\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x229983\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22James\\x20Tarkowski\\x22,\\x22lastAction\\x22\\x3A\\x22Cross\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645723\\x22,\\x22minute\\x22\\x3A\\x2215\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.840999984741211\\x22,\\x22Y\\x22\\x3A\\x220.33599998474121096\\x22,\\x22xG\\x22\\x3A\\x220.07146254181861877\\x22,\\x22player\\x22\\x3A\\x22Iliman\\x20Ndiaye\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x229307\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Kiernan\\x20Dewsbury\\x2DHall\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645725\\x22,\\x22minute\\x22\\x3A\\x2217\\x22,\\x22result\\x22\\x3A\\x22Goal\\x22,\\x22X\\x22\\x3A\\x220.895\\x22,\\x22Y\\x22\\x3A\\x220.5220000076293946\\x22,\\x22xG\\x22\\x3A\\x220.06543771922588348\\x22,\\x22player\\x22\\x3A\\x22Michael\\x20Keane\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x221653\\x22,\\x22situation\\x22\\x3A\\x22FromCorner\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22lastAction\\x22\\x3A\\x22Cross\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645727\\x22,\\x22minute\\x22\\x3A\\x2234\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.9009999847412109\\x22,\\x22Y\\x22\\x3A\\x220.5520000076293945\\x22,\\x22xG\\x22\\x3A\\x220.03163493052124977\\x22,\\x22player\\x22\\x3A\\x22Kiernan\\x20Dewsbury\\x2DHall\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x229739\\x22,\\x22situation\\x22\\x3A\\x22SetPiece\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Iliman\\x20Ndiaye\\x22,\\x22lastAction\\x22\\x3A\\x22Aerial\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645729\\x22,\\x22minute\\x22\\x3A\\x2247\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.9359999847412109\\x22,\\x22Y\\x22\\x3A\\x220.33099998474121095\\x22,\\x22xG\\x22\\x3A\\x220.07636772096157074\\x22,\\x22player\\x22\\x3A\\x22Jake\\x20O\\x26\\x23039\\x3BBrien\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x2212014\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22None\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645730\\x22,\\x22minute\\x22\\x3A\\x2248\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.8219999694824218\\x22,\\x22Y\\x22\\x3A\\x220.39099998474121095\\x22,\\x22xG\\x22\\x3A\\x220.040562789887189865\\x22,\\x22player\\x22\\x3A\\x22Idrissa\\x20Gueye\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x22668\\x22,\\x22situation\\x22\\x3A\\x22FromCorner\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Jack\\x20Grealish\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645731\\x22,\\x22minute\\x22\\x3A\\x2249\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.884000015258789\\x22,\\x22Y\\x22\\x3A\\x220.3290000152587891\\x22,\\x22xG\\x22\\x3A\\x220.08038363605737686\\x22,\\x22player\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x227438\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Iliman\\x20Ndiaye\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645732\\x22,\\x22minute\\x22\\x3A\\x2251\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.8440000152587891\\x22,\\x22Y\\x22\\x3A\\x220.5820000076293945\\x22,\\x22xG\\x22\\x3A\\x220.08670539408922195\\x22,\\x22player\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x227438\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Jack\\x20Grealish\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645734\\x22,\\x22minute\\x22\\x3A\\x2255\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.850999984741211\\x22,\\x22Y\\x22\\x3A\\x220.5770000076293945\\x22,\\x22xG\\x22\\x3A\\x220.08681735396385193\\x22,\\x22player\\x22\\x3A\\x22Kiernan\\x20Dewsbury\\x2DHall\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x229739\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Jack\\x20Grealish\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645735\\x22,\\x22minute\\x22\\x3A\\x2257\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.855\\x22,\\x22Y\\x22\\x3A\\x220.30700000762939456\\x22,\\x22xG\\x22\\x3A\\x220.027368303388357162\\x22,\\x22player\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x227438\\x22,\\x22situation\\x22\\x3A\\x22FromCorner\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22None\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645742\\x22,\\x22minute\\x22\\x3A\\x2282\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.7980000305175782\\x22,\\x22Y\\x22\\x3A\\x220.785\\x22,\\x22xG\\x22\\x3A\\x220.04392853006720543\\x22,\\x22player\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x227438\\x22,\\x22situation\\x22\\x3A\\x22DirectFreekick\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22Standard\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645745\\x22,\\x22minute\\x22\\x3A\\x2289\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.8159999847412109\\x22,\\x22Y\\x22\\x3A\\x220.6029999923706054\\x22,\\x22xG\\x22\\x3A\\x220.03966496139764786\\x22,\\x22player\\x22\\x3A\\x22James\\x20Garner\\x22,\\x22h_a\\x22\\x3A\\x22h\\x22,\\x22player_id\\x22\\x3A\\x227438\\x22,\\x22situation\\x22\\x3A\\x22SetPiece\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Jack\\x20Grealish\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D\\x5D,\\x22a\\x22\\x3A\\x5B\\x7B\\x22id\\x22\\x3A\\x22645720\\x22,\\x22minute\\x22\\x3A\\x228\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.825999984741211\\x22,\\x22Y\\x22\\x3A\\x220.5379999923706055\\x22,\\x22xG\\x22\\x3A\\x220.07278106361627579\\x22,\\x22player\\x22\\x3A\\x22Lucas\\x20Paquet\\x5Cu00e1\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x227365\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Niclas\\x20F\\x5Cu00fcllkrug\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645721\\x22,\\x22minute\\x22\\x3A\\x2212\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.8719999694824219\\x22,\\x22Y\\x22\\x3A\\x220.39299999237060546\\x22,\\x22xG\\x22\\x3A\\x220.07681732624769211\\x22,\\x22player\\x22\\x3A\\x22Crysencio\\x20Summerville\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x229492\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Niclas\\x20F\\x5Cu00fcllkrug\\x22,\\x22lastAction\\x22\\x3A\\x22BallTouch\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645724\\x22,\\x22minute\\x22\\x3A\\x2215\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.875999984741211\\x22,\\x22Y\\x22\\x3A\\x220.49700000762939456\\x22,\\x22xG\\x22\\x3A\\x220.07815655320882797\\x22,\\x22player\\x22\\x3A\\x22Niclas\\x20F\\x5Cu00fcllkrug\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x226098\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Crysencio\\x20Summerville\\x22,\\x22lastAction\\x22\\x3A\\x22Cross\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645726\\x22,\\x22minute\\x22\\x3A\\x2225\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.9430000305175781\\x22,\\x22Y\\x22\\x3A\\x220.5459999847412109\\x22,\\x22xG\\x22\\x3A\\x220.06523264199495316\\x22,\\x22player\\x22\\x3A\\x22Niclas\\x20F\\x5Cu00fcllkrug\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x226098\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Max\\x20Kilman\\x22,\\x22lastAction\\x22\\x3A\\x22Aerial\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645728\\x22,\\x22minute\\x22\\x3A\\x2236\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.945\\x22,\\x22Y\\x22\\x3A\\x220.4129999923706055\\x22,\\x22xG\\x22\\x3A\\x220.044574204832315445\\x22,\\x22player\\x22\\x3A\\x22Konstantinos\\x20Mavropanos\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x226722\\x22,\\x22situation\\x22\\x3A\\x22SetPiece\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Lucas\\x20Paquet\\x5Cu00e1\\x22,\\x22lastAction\\x22\\x3A\\x22Aerial\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645733\\x22,\\x22minute\\x22\\x3A\\x2254\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.725999984741211\\x22,\\x22Y\\x22\\x3A\\x220.39099998474121095\\x22,\\x22xG\\x22\\x3A\\x220.015659164637327194\\x22,\\x22player\\x22\\x3A\\x22Mateus\\x20Fernandes\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x2212948\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Kyle\\x20Walker\\x2DPeters\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645736\\x22,\\x22minute\\x22\\x3A\\x2257\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.830999984741211\\x22,\\x22Y\\x22\\x3A\\x220.705\\x22,\\x22xG\\x22\\x3A\\x220.027432063594460487\\x22,\\x22player\\x22\\x3A\\x22Crysencio\\x20Summerville\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x229492\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22None\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645737\\x22,\\x22minute\\x22\\x3A\\x2262\\x22,\\x22result\\x22\\x3A\\x22SavedShot\\x22,\\x22X\\x22\\x3A\\x220.909000015258789\\x22,\\x22Y\\x22\\x3A\\x220.505\\x22,\\x22xG\\x22\\x3A\\x220.08749948441982269\\x22,\\x22player\\x22\\x3A\\x22Crysencio\\x20Summerville\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x229492\\x22,\\x22situation\\x22\\x3A\\x22SetPiece\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22RightFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22None\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645738\\x22,\\x22minute\\x22\\x3A\\x2264\\x22,\\x22result\\x22\\x3A\\x22Goal\\x22,\\x22X\\x22\\x3A\\x220.8719999694824219\\x22,\\x22Y\\x22\\x3A\\x220.27399999618530274\\x22,\\x22xG\\x22\\x3A\\x220.061372317373752594\\x22,\\x22player\\x22\\x3A\\x22Jarrod\\x20Bowen\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x221776\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3Anull,\\x22lastAction\\x22\\x3A\\x22None\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645739\\x22,\\x22minute\\x22\\x3A\\x2271\\x22,\\x22result\\x22\\x3A\\x22BlockedShot\\x22,\\x22X\\x22\\x3A\\x220.9030000305175782\\x22,\\x22Y\\x22\\x3A\\x220.3189999961853027\\x22,\\x22xG\\x22\\x3A\\x220.07005307078361511\\x22,\\x22player\\x22\\x3A\\x22Jarrod\\x20Bowen\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x221776\\x22,\\x22situation\\x22\\x3A\\x22OpenPlay\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22LeftFoot\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Lucas\\x20Paquet\\x5Cu00e1\\x22,\\x22lastAction\\x22\\x3A\\x22Pass\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645740\\x22,\\x22minute\\x22\\x3A\\x2272\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.9209999847412109\\x22,\\x22Y\\x22\\x3A\\x220.4540000152587891\\x22,\\x22xG\\x22\\x3A\\x220.036147017031908035\\x22,\\x22player\\x22\\x3A\\x22Konstantinos\\x20Mavropanos\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id\\x22\\x3A\\x226722\\x22,\\x22situation\\x22\\x3A\\x22FromCorner\\x22,\\x22season\\x22\\x3A\\x222025\\x22,\\x22shotType\\x22\\x3A\\x22Head\\x22,\\x22match_id\\x22\\x3A\\x2228837\\x22,\\x22h_team\\x22\\x3A\\x22Everton\\x22,\\x22a_team\\x22\\x3A\\x22West\\x20Ham\\x22,\\x22h_goals\\x22\\x3A\\x221\\x22,\\x22a_goals\\x22\\x3A\\x221\\x22,\\x22date\\x22\\x3A\\x222025\\x2D09\\x2D29\\x2019\\x3A00\\x3A00\\x22,\\x22player_assisted\\x22\\x3A\\x22Lucas\\x20Paquet\\x5Cu00e1\\x22,\\x22lastAction\\x22\\x3A\\x22Aerial\\x22\\x7D,\\x7B\\x22id\\x22\\x3A\\x22645741\\x22,\\x22minute\\x22\\x3A\\x2279\\x22,\\x22result\\x22\\x3A\\x22MissedShots\\x22,\\x22X\\x22\\x3A\\x220.7880000305175782\\x22,\\x22Y\\x22\\x3A\\x220.669000015258789\\x22,\\x22xG\\x22\\x3A\\x220.017835404723882675\\x22,\\x22player\\x22\\x3A\\x22El\\x20Hadji\\x20Malick\\x20Diouf\\x22,\\x22h_a\\x22\\x3A\\x22a\\x22,\\x22player_id

In [27]:
data=shots_data.encode("utf8").decode("unicode_escape")

In [28]:
data

'{"h":[{"id":"645722","minute":"14","result":"SavedShot","X":"0.9109999847412109","Y":"0.455","xG":"0.259369432926178","player":"Beto","h_a":"h","player_id":"9983","situation":"OpenPlay","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"James Tarkowski","lastAction":"Cross"},{"id":"645723","minute":"15","result":"SavedShot","X":"0.840999984741211","Y":"0.33599998474121096","xG":"0.07146254181861877","player":"Iliman Ndiaye","h_a":"h","player_id":"9307","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Kiernan Dewsbury-Hall","lastAction":"Pass"},{"id":"645725","minute":"17","result":"Goal","X":"0.895","Y":"0.5220000076293946","xG":"0.06543771922588348","player":"Michael Keane","h_a":"h","player_id":"1653","situation":"FromCorner","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"James Garner","lastAction":"Cross"},{"id":"645727","minute":"34","result":"MissedShots","X":"0.9009999847412109","Y":"0.5520000076293945","xG":"0.03163493052124977","player":"Kiernan Dewsbury-Hall","h_a":"h","player_id":"9739","situation":"SetPiece","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Iliman Ndiaye","lastAction":"Aerial"},{"id":"645729","minute":"47","result":"BlockedShot","X":"0.9359999847412109","Y":"0.33099998474121095","xG":"0.07636772096157074","player":"Jake O&#039;Brien","h_a":"h","player_id":"12014","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645730","minute":"48","result":"MissedShots","X":"0.8219999694824218","Y":"0.39099998474121095","xG":"0.040562789887189865","player":"Idrissa Gueye","h_a":"h","player_id":"668","situation":"FromCorner","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Jack Grealish","lastAction":"Pass"},{"id":"645731","minute":"49","result":"BlockedShot","X":"0.884000015258789","Y":"0.3290000152587891","xG":"0.08038363605737686","player":"James Garner","h_a":"h","player_id":"7438","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Iliman Ndiaye","lastAction":"Pass"},{"id":"645732","minute":"51","result":"SavedShot","X":"0.8440000152587891","Y":"0.5820000076293945","xG":"0.08670539408922195","player":"James Garner","h_a":"h","player_id":"7438","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Jack Grealish","lastAction":"Pass"},{"id":"645734","minute":"55","result":"BlockedShot","X":"0.850999984741211","Y":"0.5770000076293945","xG":"0.08681735396385193","player":"Kiernan Dewsbury-Hall","h_a":"h","player_id":"9739","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Jack Grealish","lastAction":"Pass"},{"id":"645735","minute":"57","result":"SavedShot","X":"0.855","Y":"0.30700000762939456","xG":"0.027368303388357162","player":"James Garner","h_a":"h","player_id":"7438","situation":"FromCorner","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645742","minute":"82","result":"MissedShots","X":"0.7980000305175782","Y":"0.785","xG":"0.04392853006720543","player":"James Garner","h_a":"h","player_id":"7438","situation":"DirectFreekick","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"Standard"},{"id":"645745","minute":"89","result":"SavedShot","X":"0.8159999847412109","Y":"0.6029999923706054","xG":"0.03966496139764786","player":"James Garner","h_a":"h","player_id":"7438","situation":"SetPiece","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Jack Grealish","lastAction":"Pass"}],"a":[{"id":"645720","minute":"8","result":"BlockedShot","X":"0.825999984741211","Y":"0.5379999923706055","xG":"0.07278106361627579","player":"Lucas Paquet\\u00e1","h_a":"a","player_id":"7365","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Niclas F\\u00fcllkrug","lastAction":"Pass"},{"id":"645721","minute":"12","result":"BlockedShot","X":"0.8719999694824219","Y":"0.39299999237060546","xG":"0.07681732624769211","player":"Crysencio Summerville","h_a":"a","player_id":"9492","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Niclas F\\u00fcllkrug","lastAction":"BallTouch"},{"id":"645724","minute":"15","result":"MissedShots","X":"0.875999984741211","Y":"0.49700000762939456","xG":"0.07815655320882797","player":"Niclas F\\u00fcllkrug","h_a":"a","player_id":"6098","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Crysencio Summerville","lastAction":"Cross"},{"id":"645726","minute":"25","result":"SavedShot","X":"0.9430000305175781","Y":"0.5459999847412109","xG":"0.06523264199495316","player":"Niclas F\\u00fcllkrug","h_a":"a","player_id":"6098","situation":"OpenPlay","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Max Kilman","lastAction":"Aerial"},{"id":"645728","minute":"36","result":"BlockedShot","X":"0.945","Y":"0.4129999923706055","xG":"0.044574204832315445","player":"Konstantinos Mavropanos","h_a":"a","player_id":"6722","situation":"SetPiece","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Lucas Paquet\\u00e1","lastAction":"Aerial"},{"id":"645733","minute":"54","result":"BlockedShot","X":"0.725999984741211","Y":"0.39099998474121095","xG":"0.015659164637327194","player":"Mateus Fernandes","h_a":"a","player_id":"12948","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Kyle Walker-Peters","lastAction":"Pass"},{"id":"645736","minute":"57","result":"MissedShots","X":"0.830999984741211","Y":"0.705","xG":"0.027432063594460487","player":"Crysencio Summerville","h_a":"a","player_id":"9492","situation":"OpenPlay","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645737","minute":"62","result":"SavedShot","X":"0.909000015258789","Y":"0.505","xG":"0.08749948441982269","player":"Crysencio Summerville","h_a":"a","player_id":"9492","situation":"SetPiece","season":"2025","shotType":"RightFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645738","minute":"64","result":"Goal","X":"0.8719999694824219","Y":"0.27399999618530274","xG":"0.061372317373752594","player":"Jarrod Bowen","h_a":"a","player_id":"1776","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645739","minute":"71","result":"BlockedShot","X":"0.9030000305175782","Y":"0.3189999961853027","xG":"0.07005307078361511","player":"Jarrod Bowen","h_a":"a","player_id":"1776","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Lucas Paquet\\u00e1","lastAction":"Pass"},{"id":"645740","minute":"72","result":"MissedShots","X":"0.9209999847412109","Y":"0.4540000152587891","xG":"0.036147017031908035","player":"Konstantinos Mavropanos","h_a":"a","player_id":"6722","situation":"FromCorner","season":"2025","shotType":"Head","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Lucas Paquet\\u00e1","lastAction":"Aerial"},{"id":"645741","minute":"79","result":"MissedShots","X":"0.7880000305175782","Y":"0.669000015258789","xG":"0.017835404723882675","player":"El Hadji Malick Diouf","h_a":"a","player_id":"13723","situation":"FromCorner","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":null,"lastAction":"None"},{"id":"645743","minute":"87","result":"BlockedShot","X":"0.9209999847412109","Y":"0.32099998474121094","xG":"0.06768626719713211","player":"Jarrod Bowen","h_a":"a","player_id":"1776","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Kyle Walker-Peters","lastAction":"Pass"},{"id":"645744","minute":"87","result":"MissedShots","X":"0.8130000305175781","Y":"0.5259999847412109","xG":"0.05451938882470131","player":"Mateus Fernandes","h_a":"a","player_id":"12948","situation":"OpenPlay","season":"2025","shotType":"LeftFoot","match_id":"28837","h_team":"Everton","a_team":"West Ham","h_goals":"1","a_goals":"1","date":"2025-09-29 19:00:00","player_assisted":"Niclas F\\u00fcllkrug","lastAction":"Pass"}]}'

In [29]:
data=json.loads(data)

In [30]:
data

{'h': [{'id': '645722',
   'minute': '14',
   'result': 'SavedShot',
   'X': '0.9109999847412109',
   'Y': '0.455',
   'xG': '0.259369432926178',
   'player': 'Beto',
   'h_a': 'h',
   'player_id': '9983',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'James Tarkowski',
   'lastAction': 'Cross'},
  {'id': '645723',
   'minute': '15',
   'result': 'SavedShot',
   'X': '0.840999984741211',
   'Y': '0.33599998474121096',
   'xG': '0.07146254181861877',
   'player': 'Iliman Ndiaye',
   'h_a': 'h',
   'player_id': '9307',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Kiernan Dewsbury-Hall',
   'lastAction': 'Pass'},
  {'id': '645725',
   'minute': '17',
   'result': 'Goal',
   'X': '0.895',
   'Y': '0.5220000076293946',
   'xG': '0.06543771922588348',
   'player': 'Michael Keane',
   'h_a': 'h',
   'player_id': '1653',
   'situation': 'FromCorner',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'James Garner',
   'lastAction': 'Cross'},
  {'id': '645727',
   'minute': '34',
   'result': 'MissedShots',
   'X': '0.9009999847412109',
   'Y': '0.5520000076293945',
   'xG': '0.03163493052124977',
   'player': 'Kiernan Dewsbury-Hall',
   'h_a': 'h',
   'player_id': '9739',
   'situation': 'SetPiece',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Iliman Ndiaye',
   'lastAction': 'Aerial'},
  {'id': '645729',
   'minute': '47',
   'result': 'BlockedShot',
   'X': '0.9359999847412109',
   'Y': '0.33099998474121095',
   'xG': '0.07636772096157074',
   'player': 'Jake O&#039;Brien',
   'h_a': 'h',
   'player_id': '12014',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645730',
   'minute': '48',
   'result': 'MissedShots',
   'X': '0.8219999694824218',
   'Y': '0.39099998474121095',
   'xG': '0.040562789887189865',
   'player': 'Idrissa Gueye',
   'h_a': 'h',
   'player_id': '668',
   'situation': 'FromCorner',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Jack Grealish',
   'lastAction': 'Pass'},
  {'id': '645731',
   'minute': '49',
   'result': 'BlockedShot',
   'X': '0.884000015258789',
   'Y': '0.3290000152587891',
   'xG': '0.08038363605737686',
   'player': 'James Garner',
   'h_a': 'h',
   'player_id': '7438',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Iliman Ndiaye',
   'lastAction': 'Pass'},
  {'id': '645732',
   'minute': '51',
   'result': 'SavedShot',
   'X': '0.8440000152587891',
   'Y': '0.5820000076293945',
   'xG': '0.08670539408922195',
   'player': 'James Garner',
   'h_a': 'h',
   'player_id': '7438',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Jack Grealish',
   'lastAction': 'Pass'},
  {'id': '645734',
   'minute': '55',
   'result': 'BlockedShot',
   'X': '0.850999984741211',
   'Y': '0.5770000076293945',
   'xG': '0.08681735396385193',
   'player': 'Kiernan Dewsbury-Hall',
   'h_a': 'h',
   'player_id': '9739',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Jack Grealish',
   'lastAction': 'Pass'},
  {'id': '645735',
   'minute': '57',
   'result': 'SavedShot',
   'X': '0.855',
   'Y': '0.30700000762939456',
   'xG': '0.027368303388357162',
   'player': 'James Garner',
   'h_a': 'h',
   'player_id': '7438',
   'situation': 'FromCorner',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645742',
   'minute': '82',
   'result': 'MissedShots',
   'X': '0.7980000305175782',
   'Y': '0.785',
   'xG': '0.04392853006720543',
   'player': 'James Garner',
   'h_a': 'h',
   'player_id': '7438',
   'situation': 'DirectFreekick',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '645745',
   'minute': '89',
   'result': 'SavedShot',
   'X': '0.8159999847412109',
   'Y': '0.6029999923706054',
   'xG': '0.03966496139764786',
   'player': 'James Garner',
   'h_a': 'h',
   'player_id': '7438',
   'situation': 'SetPiece',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Jack Grealish',
   'lastAction': 'Pass'}],
 'a': [{'id': '645720',
   'minute': '8',
   'result': 'BlockedShot',
   'X': '0.825999984741211',
   'Y': '0.5379999923706055',
   'xG': '0.07278106361627579',
   'player': 'Lucas Paquetá',
   'h_a': 'a',
   'player_id': '7365',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Niclas Füllkrug',
   'lastAction': 'Pass'},
  {'id': '645721',
   'minute': '12',
   'result': 'BlockedShot',
   'X': '0.8719999694824219',
   'Y': '0.39299999237060546',
   'xG': '0.07681732624769211',
   'player': 'Crysencio Summerville',
   'h_a': 'a',
   'player_id': '9492',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Niclas Füllkrug',
   'lastAction': 'BallTouch'},
  {'id': '645724',
   'minute': '15',
   'result': 'MissedShots',
   'X': '0.875999984741211',
   'Y': '0.49700000762939456',
   'xG': '0.07815655320882797',
   'player': 'Niclas Füllkrug',
   'h_a': 'a',
   'player_id': '6098',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Crysencio Summerville',
   'lastAction': 'Cross'},
  {'id': '645726',
   'minute': '25',
   'result': 'SavedShot',
   'X': '0.9430000305175781',
   'Y': '0.5459999847412109',
   'xG': '0.06523264199495316',
   'player': 'Niclas Füllkrug',
   'h_a': 'a',
   'player_id': '6098',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Max Kilman',
   'lastAction': 'Aerial'},
  {'id': '645728',
   'minute': '36',
   'result': 'BlockedShot',
   'X': '0.945',
   'Y': '0.4129999923706055',
   'xG': '0.044574204832315445',
   'player': 'Konstantinos Mavropanos',
   'h_a': 'a',
   'player_id': '6722',
   'situation': 'SetPiece',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Lucas Paquetá',
   'lastAction': 'Aerial'},
  {'id': '645733',
   'minute': '54',
   'result': 'BlockedShot',
   'X': '0.725999984741211',
   'Y': '0.39099998474121095',
   'xG': '0.015659164637327194',
   'player': 'Mateus Fernandes',
   'h_a': 'a',
   'player_id': '12948',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Kyle Walker-Peters',
   'lastAction': 'Pass'},
  {'id': '645736',
   'minute': '57',
   'result': 'MissedShots',
   'X': '0.830999984741211',
   'Y': '0.705',
   'xG': '0.027432063594460487',
   'player': 'Crysencio Summerville',
   'h_a': 'a',
   'player_id': '9492',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645737',
   'minute': '62',
   'result': 'SavedShot',
   'X': '0.909000015258789',
   'Y': '0.505',
   'xG': '0.08749948441982269',
   'player': 'Crysencio Summerville',
   'h_a': 'a',
   'player_id': '9492',
   'situation': 'SetPiece',
   'season': '2025',
   'shotType': 'RightFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645738',
   'minute': '64',
   'result': 'Goal',
   'X': '0.8719999694824219',
   'Y': '0.27399999618530274',
   'xG': '0.061372317373752594',
   'player': 'Jarrod Bowen',
   'h_a': 'a',
   'player_id': '1776',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645739',
   'minute': '71',
   'result': 'BlockedShot',
   'X': '0.9030000305175782',
   'Y': '0.3189999961853027',
   'xG': '0.07005307078361511',
   'player': 'Jarrod Bowen',
   'h_a': 'a',
   'player_id': '1776',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Lucas Paquetá',
   'lastAction': 'Pass'},
  {'id': '645740',
   'minute': '72',
   'result': 'MissedShots',
   'X': '0.9209999847412109',
   'Y': '0.4540000152587891',
   'xG': '0.036147017031908035',
   'player': 'Konstantinos Mavropanos',
   'h_a': 'a',
   'player_id': '6722',
   'situation': 'FromCorner',
   'season': '2025',
   'shotType': 'Head',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Lucas Paquetá',
   'lastAction': 'Aerial'},
  {'id': '645741',
   'minute': '79',
   'result': 'MissedShots',
   'X': '0.7880000305175782',
   'Y': '0.669000015258789',
   'xG': '0.017835404723882675',
   'player': 'El Hadji Malick Diouf',
   'h_a': 'a',
   'player_id': '13723',
   'situation': 'FromCorner',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '645743',
   'minute': '87',
   'result': 'BlockedShot',
   'X': '0.9209999847412109',
   'Y': '0.32099998474121094',
   'xG': '0.06768626719713211',
   'player': 'Jarrod Bowen',
   'h_a': 'a',
   'player_id': '1776',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Kyle Walker-Peters',
   'lastAction': 'Pass'},
  {'id': '645744',
   'minute': '87',
   'result': 'MissedShots',
   'X': '0.8130000305175781',
   'Y': '0.5259999847412109',
   'xG': '0.05451938882470131',
   'player': 'Mateus Fernandes',
   'h_a': 'a',
   'player_id': '12948',
   'situation': 'OpenPlay',
   'season': '2025',
   'shotType': 'LeftFoot',
   'match_id': '28837',
   'h_team': 'Everton',
   'a_team': 'West Ham',
   'h_goals': '1',
   'a_goals': '1',
   'date': '2025-09-29 19:00:00',
   'player_assisted': 'Niclas Füllkrug',
   'lastAction': 'Pass'}]}